  ros_control_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      lwr_arm_0_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_1_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_2_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_3_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_4_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_5_joint: {trajectory: 0.1, goal: 0.1}
      lwr_arm_6_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
